version: '3.9'
services:
  mysql:
    container_name: 'crud-rest-api'
    command: '--default-authentication-plugin=mysql_native_password'
    image: 'mysql:8-debian'
    ports:
      - '3306:3306'
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
      - 'data-mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'crud-rest-api'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
volumes:
  data-mysql:
